file -inlinebatch EOB

CREATE TABLE TABLE0 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE0 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE0 ON COLUMN PK;
CREATE INDEX IDX_TABLE0 ON TABLE0 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE1 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE1 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE1 ON COLUMN PK;
CREATE INDEX IDX_TABLE1 ON TABLE1 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE2 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE2 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE2 ON COLUMN PK;
CREATE INDEX IDX_TABLE2 ON TABLE2 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE3 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE3 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE3 ON COLUMN PK;
CREATE INDEX IDX_TABLE3 ON TABLE3 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE4 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE4 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE4 ON COLUMN PK;
CREATE INDEX IDX_TABLE4 ON TABLE4 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE5 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE5 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE5 ON COLUMN PK;
CREATE INDEX IDX_TABLE5 ON TABLE5 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE6 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE6 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE6 ON COLUMN PK;
CREATE INDEX IDX_TABLE6 ON TABLE6 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE7 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE7 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE7 ON COLUMN PK;
CREATE INDEX IDX_TABLE7 ON TABLE7 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE8 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE8 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE8 ON COLUMN PK;
CREATE INDEX IDX_TABLE8 ON TABLE8 (PK, VALUE1, VALUE2);

CREATE TABLE TABLE9 (
   FLAG tinyint DEFAULT '0' NOT NULL,
   PK BIGINT NOT NULL,
   VALUE1 varchar(50 BYTES),
   VALUE2 varchar(50 BYTES),
   VALUE3 varchar(50 BYTES),
   CONSTRAINT PK_TABLE9 PRIMARY KEY (PK)
);
PARTITION TABLE TABLE9 ON COLUMN PK;
CREATE INDEX IDX_TABLE9 ON TABLE9 (PK, VALUE1, VALUE2);

EOB
